---
- name: Determine system architecture
  shell: uname -m
  register: arch
  changed_when: false

- name: Set Cilium CLI architecture
  set_fact:
    cilium_arch: "{{ 'arm64' if arch.stdout == 'aarch64' else 'amd64' }}"

- name: Download Cilium CLI
  shell: |
    CILIUM_CLI_VERSION=$(curl -s https://raw.githubusercontent.com/cilium/cilium-cli/main/stable.txt)
    curl -L --fail --remote-name-all https://github.com/cilium/cilium-cli/releases/download/${CILIUM_CLI_VERSION}/cilium-linux-{{ cilium_arch }}.tar.gz{,.sha256sum}
    sha256sum --check cilium-linux-{{ cilium_arch }}.tar.gz.sha256sum
    sudo tar xzvfC cilium-linux-{{ cilium_arch }}.tar.gz /usr/local/bin
    rm cilium-linux-{{ cilium_arch }}.tar.gz{,.sha256sum}
  args:
    executable: /bin/bash

- name: Install Cilium
  shell: |
    export KUBECONFIG=/etc/rancher/k3s/k3s.yaml
    cilium install --version {{ cilium_version }} --set=ipam.operator.clusterPoolIPv4PodCIDRList="{{ pod_cidr }}"
  args:
    executable: /bin/bash

- name: Validate Cilium installation
  shell: |
    export KUBECONFIG=/etc/rancher/k3s/k3s.yaml
    cilium status --wait
  args:
    executable: /bin/bash
  register: cilium_status

- name: Display Cilium status
  debug:
    var: cilium_status.stdout
